#!/bin/bash
export PATH=${HOME}/bin:${HOME}/.local/bin:${PATH}
dex -a -e Awesome >>  $HOME/.Xsession.log 2>&1
xrdb -load ~/.Xresources >> $HOME/.Xsession.log 2>&1
exec awesome >> $HOME/.Xsession.log 2>&1
